name: ${project.name}
version: ${project.version}
description: ${project.description}
author: cnaude
main: com.cnaude.trophyheads.TrophyHeads
softdepend:
  - Carbon
commands:
    headspawn:
        description: Spawn the head of a player
        aliases: [head]
        usage: /headspawn [player] ([count])
    headgive:
        description: Spawn the head of a player
        aliases: [headg]
        usage: /headspawn [player] [skull name] ([count])
    trophyreload:
        description: Reload configuration
        aliases: [threload,thr]
        usage: /reophyreload
permissions:
  'trophyheads.spawn':
    description: Gives player access to the /headspawn command.
    default: op
  'trophyheads.give':
    description: Gives player access to the /headgive command.
    default: op    
  'trophyheads.drop':
    description: Allows players to randomly drop heads at death.
    default: true
  'trophyheads.info':
    description: Allows players to punch a skull to see who the owner was.
    default: true
  'trophyheads.reload':
    description: Allows players to reload configuration.
    default: op
